### ISSUE TITLE
Various Locations (PDF Only): Pagination

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st429-16#16]
- 5.3: Move heading to next page.
- Clause 6: Move heading to next page.
- 6.1, Table 3: Header row is on different page from the body of the table.
- 6.1, Table 3: Table is cut off after first page of main body of table. Full table is visible in the HTML version.
- Annex A, Table A.1: Header row is on different page from the body of the table.
- Annex A, Table A.1: Table is cut off after first page of main body of table. Full table is visible in the HTML version.

**Comment by palemieux** [comment]
Fixed at https://github.com/SMPTE/st429-16-private/commit/d2821e0774e2194ea87f341a4e78e1da123ebdcb

https://doc.smpte-doc.org/st429-16-private/d2821e0774e2194ea87f341a4e78e1da123ebdcb/SMPTE%20ST%20429-16%20D-Cinema%20Packaging%20-%20Additional%20Composition%20Metadata%20and%20Guidelines.pdf

**Comment by ERyan71258** [comment]
Looks good. The link directly following "Fixed at", however, opens a 404 page.
The second link properly opens the PDF.

**Comment by palemieux** [comment]
I added you to the repo.

**Comment by ERyan71258** [comment]
Thanks!
