### ISSUE TITLE
6.2, Paragraph 3: Incorrect Links?

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st429-16#47]
The paragraph states:
"The language tags listed in Annex B should be used whenever possible. The obsolete codes listed in Annex B shall not be used."

Annex B is titled "Example Instance".
Annex A is titled "Common Language Tags and Obsolete Codes".
- I believe that in the paragraph, both instances of "Annex B" should be replaced by "Annex A".
- Once corrected, add hyperlinks.

**Comment by palemieux** [comment]
Duplicate of #50
