### ISSUE TITLE
"FSKSync" is not a valid channel identifier for MainSoundConfiguration element

### ISSUE THREAD

**Issue by cfadamp** [SMPTE/st429-16#8]
In section 4.4.2.10 MainSoundConfiguration the format of the identifiers are defined as
```
MAINSOUND = SOUNDFIELD ["/" CHANNEL *("," CHANNEL)]
SOUNDFIELD = TOKEN 
CHANNEL = "-" / TOKEN 
TOKEN = 1*6(ALPHA / DIGIT)
```

but if I use a Dolby ATMOS track in my composition and have a sync channel in 14th channel of the main audio track, and I would like to flag this in the MainSoundConfiguration element with the "FSKSync" identifier (SMPTE ST 430-12:2014
Amendment 1:2019) then it will be invalid as it is 7 characters long.

I would also suggest to replace the current XSD:
``` <xs:element name="MainSoundConfiguration" minOccurs="1" type="xs:string"/> ```
to a more accurate element, for example:
```
<xs:element name="MainSoundConfiguration" minOccurs="1" >
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]{1,6}/((-|[a-zA-Z0-9]{1,6}))(,(-|[a-zA-Z0-9]{1,6}))*" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>

```

To demonstrate, the following MainSoundConfiguration element of a MainSound track of a CPL with Dolby ATMOS track is not valid
``` <MainSoundConfiguration>51/L,R,C,LFE,Ls,Rs,-,-,-,-,-,-,-,FSKSync,-,-</MainSoundConfiguration> ```
and it will fail on my XSD schema check as well.

**Comment by palemieux** [comment]
Couple of observations:

* the syntax of `MainSoundConfiguration` is a recommendation ("SHOULD") and not a requirement. In other words, no validator should fail a CPL that does not conform to the syntax at 4.4.2.10, e.g. if `FSKSync` is used a `CHANNEL` value.
* accordingly ST 429-16 does not specific an XML schema for `MainSoundConfiguration`
* ST 428-12 requires that _a Symbol shall consist of a minimum of 1 and a maximum of 6 ASCII characters in the set `{0x30..0x39, 0x41..0x5A, 0x61..0x7A}`. Mixed-case is used for readability_, so ST 430-12 did not follow that guideline, but then again ST 430-12 is a loudspeaker channel

My suggestion:
* relax the `TOKEN` syntax in ST 429-16 to maybe `TOKEN = 1*8(ALPHA / DIGIT)`.
* remove the _NOTE_ at 4.4.2.10 and instead provide examples, including one with `FSKSync`

**Comment by dcbullock** [comment]
+1 @palemieux suggestion.

----

In addition, should we modify 428-12 5.4 to match:  "... and a maximum of 8 ASCII ..." ?

If we want to avoid have two definitions for channel strings we could move the ABNF from 429-16 to 428-12 and reference 428-12 from 429-16.  Or vice versa.  (If 428-12 is included in this SMPTE project.)

**Comment by SteveLLamb** [comment]
428-12 is not included. But I plan on opening both this and 428-12 for another revision for blank sound field and other sound field group tokens immediately after this revision. We can include these changes as well with all that.

**Comment by palemieux** [comment]
> In addition, should we modify 428-12 5.4 to match: "... and a maximum of 8 ASCII ..." ?

@dcbullock Unfortunately that is not possible since MCA limits `Tag Symbol` to 8 characters, so the ST 428-12 symbol needs to be limited to 6 characters,

**Comment by dcbullock** [comment]
Oh, the tangled webs....  Indeed.  I wonder if there are MainSound MXF files in the wild that include chFSKSync.

I also wonder about the impact if we changed 430-12 instead.  Our (Dolby) tools might need an update eventually.  Others?  Do any fielded playback tools care of the MCA label for 430-12 changes?

**Comment by palemieux** [comment]
> Oh, the tangled webs.... Indeed. I wonder if there are MainSound MXF files in the wild that include chFSKSync.

I hope not since ST 430-12 clearly specifies _MCA Tag Symbol:	FSKSync_

**Comment by radford-for-smpte** [comment]
> > Oh, the tangled webs.... Indeed. I wonder if there are MainSound MXF files in the wild that include chFSKSync.
> 
> I hope not since ST 430-12 clearly specifies _MCA Tag Symbol: FSKSync_

Indeed, from a recent title:

```xml
            <r0:AudioChannelLabelSubDescriptor>
              <r1:InstanceID>urn:uuid:9ad6e760-f1d5-4426-a86c-dc09e061439b</r1:InstanceID>
              <r1:MCALabelDictionaryID>urn:smpte:ul:060e2b34.0401010d.03020110.00000000</r1:MCALabelDictionaryID>
              <r1:MCALinkID>urn:uuid:bdb01e71-85de-4f0e-8b22-cb86d6b51aa3</r1:MCALinkID>
              <r1:MCATagSymbol>chFSKSync</r1:MCATagSymbol>
              <r1:MCATagName>FSK Sync</r1:MCATagName>
              <r1:MCAChannelID>14</r1:MCAChannelID>
              <r1:RFC5646SpokenLanguage>en</r1:RFC5646SpokenLanguage>
            </r0:AudioChannelLabelSubDescriptor>
```

**Comment by dcbullock** [comment]
From a newly generated test track.

<code>
060e2b34.02530101.0d010101.01016b00  len:     114 (AudioChannelLabelSubDescriptor)
             InstanceUID = 9a4119e0-5cc1-4b5c-bc2a-22dc9c4f1552
    MCALabelDictionaryID = 060e2b34.0401010d.03020110.00000000
               MCALinkID = 62549596-532e-42b4-a795-66b4fe6e7964
            MCATagSymbol = chFSKSync
              MCATagName = FSK Sync
            MCAChannelID = 14
</code>

<code>
000016b0  fd 00 10 62 54 95 96 53  2e 42 b4 a7 95 66 b4 fe  |...bT..S.B...f..|
000016c0  6e 79 64 ff fc 00 12 00  63 00 68 00 46 00 53 00  |nyd.....c.h.F.S.|
000016d0  4b 00 53 00 79 00 6e 00  63 ff fb 00 10 00 46 00  |K.S.y.n.c.....F.|
000016e0  53 00 4b 00 20 00 53 00  79 00 6e 00 63 ff f9 00  |S.K. .S.y.n.c...|
000016f0  04 00 00 00 0e ff fa 00  00 06 0e 2b 34 01 01 01  |...........+4...|
00001700  02 03 01 02 10 01 00 00  00 83 00 28 f3 00 00 00  |...........(....|
00001710  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
</code>

**Comment by dcbullock** [comment]
$20 says it was my commit....  Sigh.

**Comment by palemieux** [comment]
Thankfully MCALabelDictionaryID is the key that implementations should use and `Tag Symbol` is just for human consumption -- in fact `MCATagName` should really be used for human consumption.

What about fixing implementations and ignoring this ever happened?

**Comment by dcbullock** [comment]
That is from 3rd party tooling.  I will check on Dolby tools in a bit.

@palemieux understood on the need to not link 428-12 and 429-16 as I was thinking.
